In [2]:
import numpy as np


arr1d = np.random.randint(1, 20, size=12)
print("Random 1D array:")
print(arr1d)


arr2d = arr1d.reshape(3, 4)
print("\nReshaped 2D array:")
print(arr2d)


arr1 = np.random.randint(1, 20, size=(2, 3))
arr2 = np.random.randint(1, 20, size=(2, 3))

print("\nArray 1:")
print(arr1)
print("\nArray 2:")
print(arr2)


arr_concat_horiz = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenated horizontally:")
print(arr_concat_horiz)


arr_concat_vert = np.concatenate((arr1, arr2), axis=0)
print("\nConcatenated vertically:")
print(arr_concat_vert)


Random 1D array:
[11 16  2 15 19 13 17  9 12 10 15  4]

Reshaped 2D array:
[[11 16  2 15]
 [19 13 17  9]
 [12 10 15  4]]

Array 1:
[[ 4  6 17]
 [ 8 15 18]]

Array 2:
[[ 7 14  7]
 [ 5  8 16]]

Concatenated horizontally:
[[ 4  6 17  7 14  7]
 [ 8 15 18  5  8 16]]

Concatenated vertically:
[[ 4  6 17]
 [ 8 15 18]
 [ 7 14  7]
 [ 5  8 16]]


In [1]:
def classify_emails(emails):
    important_keywords = ['urgent', 'important', 'action required', 'deadline']
    promotion_keywords = ['sale', 'discount', 'offer', 'limited time']
    spam_keywords = ['lottery', 'inheritance', 'free', 'click here']

    important_emails = []
    promotion_emails = []
    spam_emails = []

    i = 0
    while i < len(emails):
        lowercase_email = emails[i].lower()
        if any(keyword in lowercase_email for keyword in important_keywords):
            important_emails.append(emails[i])
        elif any(keyword in lowercase_email for keyword in promotion_keywords):
            promotion_emails.append(emails[i])
        elif any(keyword in lowercase_email for keyword in spam_keywords):
            spam_emails.append(emails[i])
        i += 1

    return important_emails, promotion_emails, spam_emails


emails = [
    "URGENT: Action Required by Deadline",
    "Great deals and offers inside! Limited time only!",
    "You've won a free vacation!",
    "Important: Meeting tomorrow",
    "Special discount offer just for you",
    "Claim your inheritance",
    "Click here for exciting opportunities"
]


important_emails, promotion_emails, spam_emails = classify_emails(emails)


print("Important Emails:")
print(important_emails)
print("\nPromotion Emails:")
print(promotion_emails)
print("\nSpam Emails:")
print(spam_emails)


Important Emails:
['URGENT: Action Required by Deadline', 'Important: Meeting tomorrow']

Promotion Emails:
['Great deals and offers inside! Limited time only!', 'Special discount offer just for you']

Spam Emails:
["You've won a free vacation!", 'Claim your inheritance', 'Click here for exciting opportunities']


In [3]:

car_translations = {
    'car': 'coche',
    'truck': 'camión',
    'van': 'furgoneta',
    'suv': 'todoterreno',
    
}


while True:
    
    car = input("Enter a car name in English (or 'exit' to quit): ").lower()

    
    if car == 'exit':
        print("Goodbye!")
        break

    
    if car in car_translations:
        
        print(f"The Spanish translation of '{car}' is '{car_translations[car]}'.")
    else:
        
        print(f"The translation of '{car}' is not available.")


Enter a car name in English (or 'exit' to quit): lamborgamber
The translation of 'lamborgamber' is not available.
Enter a car name in English (or 'exit' to quit): exit
Goodbye!


In [4]:
import pandas as pd

# Load the dataset
dataset_url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
game_data = pd.read_csv(dataset_url)


print("First few rows of the dataset:")
print(game_data.head())


total_global_sales = game_data['Global_Sales'].sum()
print("\nTotal global sales for all games:", total_global_sales)


highest_sales_game = game_data.loc[game_data['Global_Sales'].idxmax()]
print("\nGame with the highest global sales:")
print(highest_sales_game)


average_sales_per_region = game_data[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("\nAverage sales for each region:")
print(average_sales_per_region)


top_5_genres_global_sales = game_data.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("\nTop 5 most popular game genres based on global sales:")
print(top_5_genres_global_sales)


total_sales_per_genre_region = game_data.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
most_popular_genre_na_sales = total_sales_per_genre_region['NA_Sales'].idxmax()
print("\nMost popular genre in North America (NA_Sales):", most_popular_genre_na_sales)


print("\nLast 10 rows of the dataset:")
print(game_data.tail(10))


top_3_platforms_global_sales = game_data.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("\nTop 3 gaming platforms with the highest global sales:")
print(top_3_platforms_global_sales)


genre_market_share = (game_data.groupby('Genre')['Global_Sales'].sum() / total_global_sales) * 100
print("\nMarket share (percentage of global sales) for each genre:")
print(genre_market_share)


correlation_coefficient = game_data['NA_Sales'].corr(game_data['EU_Sales'])
print("\nCorrelation coefficient between NA_Sales and EU_Sales:", correlation_coefficient)


First few rows of the dataset:
   Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37  

Total global sales for all games: 8920.44

Game with the highest global sales:
Rank                     1
Name            Wii Sports
